//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from G:\SOFTWARE\SW INTERNO\ParserVTL\VTL_Editor_PL\VTL_Editor_PL\Combined1.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace VTLlib {
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;

    [System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public partial class TagExpressionLexer : Lexer {
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, Tag=6, WS=7;
	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "Tag", "WS"
	};


	public TagExpressionLexer(ICharStream input)
		: base(input)
	{
		_interp = new LexerATNSimulator(this,_ATN);
	}

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "'&'", "'|'", "'!'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, "Tag", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[System.Obsolete("Use Vocabulary instead.")]
	public static readonly string[] tokenNames = GenerateTokenNames(DefaultVocabulary, _SymbolicNames.Length);

	private static string[] GenerateTokenNames(IVocabulary vocabulary, int length) {
		string[] tokenNames = new string[length];
		for (int i = 0; i < tokenNames.Length; i++) {
			tokenNames[i] = vocabulary.GetLiteralName(i);
			if (tokenNames[i] == null) {
				tokenNames[i] = vocabulary.GetSymbolicName(i);
			}

			if (tokenNames[i] == null) {
				tokenNames[i] = "<INVALID>";
			}
		}

		return tokenNames;
	}

	[System.Obsolete]
	public override string[] TokenNames
	{
		get
		{
			return tokenNames;
		}
	}

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Combined1.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	public static readonly string _serializedATN =
		"\x3\xAF6F\x8320\x479D\xB75C\x4880\x1605\x191C\xAB37\x2\t\'\b\x1\x4\x2"+
		"\t\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6\x4\a\t\a\x4\b\t\b\x3"+
		"\x2\x3\x2\x3\x3\x3\x3\x3\x4\x3\x4\x3\x5\x3\x5\x3\x6\x3\x6\x3\a\x6\a\x1D"+
		"\n\a\r\a\xE\a\x1E\x3\b\x6\b\"\n\b\r\b\xE\b#\x3\b\x3\b\x2\x2\x2\t\x3\x2"+
		"\x3\x5\x2\x4\a\x2\x5\t\x2\x6\v\x2\a\r\x2\b\xF\x2\t\x3\x2\x4\x4\x2\x43"+
		"\\\x63|\x5\x2\v\f\xF\xF\"\"(\x2\x3\x3\x2\x2\x2\x2\x5\x3\x2\x2\x2\x2\a"+
		"\x3\x2\x2\x2\x2\t\x3\x2\x2\x2\x2\v\x3\x2\x2\x2\x2\r\x3\x2\x2\x2\x2\xF"+
		"\x3\x2\x2\x2\x3\x11\x3\x2\x2\x2\x5\x13\x3\x2\x2\x2\a\x15\x3\x2\x2\x2\t"+
		"\x17\x3\x2\x2\x2\v\x19\x3\x2\x2\x2\r\x1C\x3\x2\x2\x2\xF!\x3\x2\x2\x2\x11"+
		"\x12\a*\x2\x2\x12\x4\x3\x2\x2\x2\x13\x14\a+\x2\x2\x14\x6\x3\x2\x2\x2\x15"+
		"\x16\a(\x2\x2\x16\b\x3\x2\x2\x2\x17\x18\a~\x2\x2\x18\n\x3\x2\x2\x2\x19"+
		"\x1A\a#\x2\x2\x1A\f\x3\x2\x2\x2\x1B\x1D\t\x2\x2\x2\x1C\x1B\x3\x2\x2\x2"+
		"\x1D\x1E\x3\x2\x2\x2\x1E\x1C\x3\x2\x2\x2\x1E\x1F\x3\x2\x2\x2\x1F\xE\x3"+
		"\x2\x2\x2 \"\t\x3\x2\x2! \x3\x2\x2\x2\"#\x3\x2\x2\x2#!\x3\x2\x2\x2#$\x3"+
		"\x2\x2\x2$%\x3\x2\x2\x2%&\b\b\x2\x2&\x10\x3\x2\x2\x2\x5\x2\x1E#\x3\b\x2"+
		"\x2";
	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
} // namespace VTL_Editor_PL
