//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from G:\SOFTWARE\SW INTERNO\ParserVTL\VTL_Editor_PL\VTL_Editor_PL\ValidationMl.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace VTLlib {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;

    /// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ValidationMlParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public interface IValidationMlVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStart([NotNull] ValidationMlParser.StartContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] ValidationMlParser.StatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] ValidationMlParser.ExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.exprOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprOr([NotNull] ValidationMlParser.ExprOrContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.exprAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprAnd([NotNull] ValidationMlParser.ExprAndContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.exprEq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprEq([NotNull] ValidationMlParser.ExprEqContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.exprExists"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprExists([NotNull] ValidationMlParser.ExprExistsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.exprComp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprComp([NotNull] ValidationMlParser.ExprCompContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.exprAdd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprAdd([NotNull] ValidationMlParser.ExprAddContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.exprMultiply"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprMultiply([NotNull] ValidationMlParser.ExprMultiplyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.exprFactor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprFactor([NotNull] ValidationMlParser.ExprFactorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.exprMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprMember([NotNull] ValidationMlParser.ExprMemberContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.exprAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprAtom([NotNull] ValidationMlParser.ExprAtomContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.variableRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableRef([NotNull] ValidationMlParser.VariableRefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.getExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGetExpr([NotNull] ValidationMlParser.GetExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.persistentDatasetID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPersistentDatasetID([NotNull] ValidationMlParser.PersistentDatasetIDContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.putExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPutExpr([NotNull] ValidationMlParser.PutExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.evalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEvalExpr([NotNull] ValidationMlParser.EvalExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.validationExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValidationExpr([NotNull] ValidationMlParser.ValidationExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.mergeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMergeExpr([NotNull] ValidationMlParser.MergeExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.hierarchyExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHierarchyExpr([NotNull] ValidationMlParser.HierarchyExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.mappingExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMappingExpr([NotNull] ValidationMlParser.MappingExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.aggrParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggrParam([NotNull] ValidationMlParser.AggrParamContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.aggregategetClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregategetClause([NotNull] ValidationMlParser.AggregategetClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.aggregateClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregateClause([NotNull] ValidationMlParser.AggregateClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.aggrFunctionClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggrFunctionClause([NotNull] ValidationMlParser.AggrFunctionClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.datasetIDGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasetIDGroup([NotNull] ValidationMlParser.DatasetIDGroupContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.caseElseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseElseClause([NotNull] ValidationMlParser.CaseElseClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.caseCaseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseCaseClause([NotNull] ValidationMlParser.CaseCaseClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.getFiltersClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGetFiltersClause([NotNull] ValidationMlParser.GetFiltersClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.getFilterClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGetFilterClause([NotNull] ValidationMlParser.GetFilterClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.datasetClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasetClause([NotNull] ValidationMlParser.DatasetClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.aggrFilterClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggrFilterClause([NotNull] ValidationMlParser.AggrFilterClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.filterClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFilterClause([NotNull] ValidationMlParser.FilterClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.ascdescClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAscdescClause([NotNull] ValidationMlParser.AscdescClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.renameClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRenameClause([NotNull] ValidationMlParser.RenameClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.aggrFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggrFunction([NotNull] ValidationMlParser.AggrFunctionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.percentileFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPercentileFunction([NotNull] ValidationMlParser.PercentileFunctionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.calcClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCalcClause([NotNull] ValidationMlParser.CalcClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.attrCalcClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttrCalcClause([NotNull] ValidationMlParser.AttrCalcClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.calcClauseItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCalcClauseItem([NotNull] ValidationMlParser.CalcClauseItemContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.calcExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCalcExpr([NotNull] ValidationMlParser.CalcExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.dropClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDropClause([NotNull] ValidationMlParser.DropClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.dropClauseItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDropClauseItem([NotNull] ValidationMlParser.DropClauseItemContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.keepClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeepClause([NotNull] ValidationMlParser.KeepClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.keepClauseItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeepClauseItem([NotNull] ValidationMlParser.KeepClauseItemContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.compareClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompareClause([NotNull] ValidationMlParser.CompareClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.inBetweenClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInBetweenClause([NotNull] ValidationMlParser.InBetweenClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.dimClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDimClause([NotNull] ValidationMlParser.DimClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.varRole"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarRole([NotNull] ValidationMlParser.VarRoleContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.bScalarExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBScalarExpr([NotNull] ValidationMlParser.BScalarExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.sExprOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSExprOr([NotNull] ValidationMlParser.SExprOrContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.sExprAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSExprAnd([NotNull] ValidationMlParser.SExprAndContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.sExprPredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSExprPredicate([NotNull] ValidationMlParser.SExprPredicateContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.scalarExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScalarExpr([NotNull] ValidationMlParser.ScalarExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.sExprAdd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSExprAdd([NotNull] ValidationMlParser.SExprAddContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.sExprFactor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSExprFactor([NotNull] ValidationMlParser.SExprFactorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.sExprAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSExprAtom([NotNull] ValidationMlParser.SExprAtomContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.componentID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponentID([NotNull] ValidationMlParser.ComponentIDContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.compOpScalarClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompOpScalarClause([NotNull] ValidationMlParser.CompOpScalarClauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.logBase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogBase([NotNull] ValidationMlParser.LogBaseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.powerExponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPowerExponent([NotNull] ValidationMlParser.PowerExponentContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.exponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExponent([NotNull] ValidationMlParser.ExponentContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.setExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetExpr([NotNull] ValidationMlParser.SetExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.varID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarID([NotNull] ValidationMlParser.VarIDContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.compOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompOp([NotNull] ValidationMlParser.CompOpContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.compOpScalar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompOpScalar([NotNull] ValidationMlParser.CompOpScalarContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] ValidationMlParser.ConstantContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.isCompl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIsCompl([NotNull] ValidationMlParser.IsComplContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="ValidationMlParser.lhperc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLhperc([NotNull] ValidationMlParser.LhpercContext context);
}
} // namespace VTL_Editor_PL
