//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from G:\SOFTWARE\SW INTERNO\ParserVTL\VTL_Editor_PL\VTL_Editor_PL\ValidationMl.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace VTLlib {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;

    /// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ValidationMlParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public interface IValidationMlListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] ValidationMlParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] ValidationMlParser.StartContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] ValidationMlParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] ValidationMlParser.StatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] ValidationMlParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] ValidationMlParser.ExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.exprOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprOr([NotNull] ValidationMlParser.ExprOrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.exprOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprOr([NotNull] ValidationMlParser.ExprOrContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.exprAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprAnd([NotNull] ValidationMlParser.ExprAndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.exprAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprAnd([NotNull] ValidationMlParser.ExprAndContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.exprEq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprEq([NotNull] ValidationMlParser.ExprEqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.exprEq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprEq([NotNull] ValidationMlParser.ExprEqContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.exprExists"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprExists([NotNull] ValidationMlParser.ExprExistsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.exprExists"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprExists([NotNull] ValidationMlParser.ExprExistsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.exprComp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprComp([NotNull] ValidationMlParser.ExprCompContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.exprComp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprComp([NotNull] ValidationMlParser.ExprCompContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.exprAdd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprAdd([NotNull] ValidationMlParser.ExprAddContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.exprAdd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprAdd([NotNull] ValidationMlParser.ExprAddContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.exprMultiply"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprMultiply([NotNull] ValidationMlParser.ExprMultiplyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.exprMultiply"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprMultiply([NotNull] ValidationMlParser.ExprMultiplyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.exprFactor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprFactor([NotNull] ValidationMlParser.ExprFactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.exprFactor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprFactor([NotNull] ValidationMlParser.ExprFactorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.exprMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprMember([NotNull] ValidationMlParser.ExprMemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.exprMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprMember([NotNull] ValidationMlParser.ExprMemberContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.exprAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprAtom([NotNull] ValidationMlParser.ExprAtomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.exprAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprAtom([NotNull] ValidationMlParser.ExprAtomContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.variableRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableRef([NotNull] ValidationMlParser.VariableRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.variableRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableRef([NotNull] ValidationMlParser.VariableRefContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.getExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGetExpr([NotNull] ValidationMlParser.GetExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.getExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGetExpr([NotNull] ValidationMlParser.GetExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.persistentDatasetID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPersistentDatasetID([NotNull] ValidationMlParser.PersistentDatasetIDContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.persistentDatasetID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPersistentDatasetID([NotNull] ValidationMlParser.PersistentDatasetIDContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.putExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPutExpr([NotNull] ValidationMlParser.PutExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.putExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPutExpr([NotNull] ValidationMlParser.PutExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.evalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEvalExpr([NotNull] ValidationMlParser.EvalExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.evalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEvalExpr([NotNull] ValidationMlParser.EvalExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.validationExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValidationExpr([NotNull] ValidationMlParser.ValidationExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.validationExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValidationExpr([NotNull] ValidationMlParser.ValidationExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.mergeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMergeExpr([NotNull] ValidationMlParser.MergeExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.mergeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMergeExpr([NotNull] ValidationMlParser.MergeExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.hierarchyExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHierarchyExpr([NotNull] ValidationMlParser.HierarchyExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.hierarchyExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHierarchyExpr([NotNull] ValidationMlParser.HierarchyExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.mappingExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMappingExpr([NotNull] ValidationMlParser.MappingExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.mappingExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMappingExpr([NotNull] ValidationMlParser.MappingExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.aggrParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAggrParam([NotNull] ValidationMlParser.AggrParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.aggrParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAggrParam([NotNull] ValidationMlParser.AggrParamContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.aggregategetClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAggregategetClause([NotNull] ValidationMlParser.AggregategetClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.aggregategetClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAggregategetClause([NotNull] ValidationMlParser.AggregategetClauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.aggregateClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAggregateClause([NotNull] ValidationMlParser.AggregateClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.aggregateClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAggregateClause([NotNull] ValidationMlParser.AggregateClauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.aggrFunctionClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAggrFunctionClause([NotNull] ValidationMlParser.AggrFunctionClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.aggrFunctionClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAggrFunctionClause([NotNull] ValidationMlParser.AggrFunctionClauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.datasetIDGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDatasetIDGroup([NotNull] ValidationMlParser.DatasetIDGroupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.datasetIDGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDatasetIDGroup([NotNull] ValidationMlParser.DatasetIDGroupContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.caseElseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseElseClause([NotNull] ValidationMlParser.CaseElseClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.caseElseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseElseClause([NotNull] ValidationMlParser.CaseElseClauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.caseCaseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseCaseClause([NotNull] ValidationMlParser.CaseCaseClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.caseCaseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseCaseClause([NotNull] ValidationMlParser.CaseCaseClauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.getFiltersClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGetFiltersClause([NotNull] ValidationMlParser.GetFiltersClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.getFiltersClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGetFiltersClause([NotNull] ValidationMlParser.GetFiltersClauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.getFilterClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGetFilterClause([NotNull] ValidationMlParser.GetFilterClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.getFilterClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGetFilterClause([NotNull] ValidationMlParser.GetFilterClauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.datasetClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDatasetClause([NotNull] ValidationMlParser.DatasetClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.datasetClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDatasetClause([NotNull] ValidationMlParser.DatasetClauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.aggrFilterClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAggrFilterClause([NotNull] ValidationMlParser.AggrFilterClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.aggrFilterClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAggrFilterClause([NotNull] ValidationMlParser.AggrFilterClauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.filterClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFilterClause([NotNull] ValidationMlParser.FilterClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.filterClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFilterClause([NotNull] ValidationMlParser.FilterClauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.ascdescClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAscdescClause([NotNull] ValidationMlParser.AscdescClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.ascdescClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAscdescClause([NotNull] ValidationMlParser.AscdescClauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.renameClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRenameClause([NotNull] ValidationMlParser.RenameClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.renameClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRenameClause([NotNull] ValidationMlParser.RenameClauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.aggrFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAggrFunction([NotNull] ValidationMlParser.AggrFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.aggrFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAggrFunction([NotNull] ValidationMlParser.AggrFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.percentileFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPercentileFunction([NotNull] ValidationMlParser.PercentileFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.percentileFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPercentileFunction([NotNull] ValidationMlParser.PercentileFunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.calcClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCalcClause([NotNull] ValidationMlParser.CalcClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.calcClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCalcClause([NotNull] ValidationMlParser.CalcClauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.attrCalcClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttrCalcClause([NotNull] ValidationMlParser.AttrCalcClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.attrCalcClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttrCalcClause([NotNull] ValidationMlParser.AttrCalcClauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.calcClauseItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCalcClauseItem([NotNull] ValidationMlParser.CalcClauseItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.calcClauseItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCalcClauseItem([NotNull] ValidationMlParser.CalcClauseItemContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.calcExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCalcExpr([NotNull] ValidationMlParser.CalcExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.calcExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCalcExpr([NotNull] ValidationMlParser.CalcExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.dropClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDropClause([NotNull] ValidationMlParser.DropClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.dropClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDropClause([NotNull] ValidationMlParser.DropClauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.dropClauseItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDropClauseItem([NotNull] ValidationMlParser.DropClauseItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.dropClauseItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDropClauseItem([NotNull] ValidationMlParser.DropClauseItemContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.keepClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeepClause([NotNull] ValidationMlParser.KeepClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.keepClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeepClause([NotNull] ValidationMlParser.KeepClauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.keepClauseItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeepClauseItem([NotNull] ValidationMlParser.KeepClauseItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.keepClauseItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeepClauseItem([NotNull] ValidationMlParser.KeepClauseItemContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.compareClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompareClause([NotNull] ValidationMlParser.CompareClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.compareClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompareClause([NotNull] ValidationMlParser.CompareClauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.inBetweenClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInBetweenClause([NotNull] ValidationMlParser.InBetweenClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.inBetweenClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInBetweenClause([NotNull] ValidationMlParser.InBetweenClauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.dimClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDimClause([NotNull] ValidationMlParser.DimClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.dimClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDimClause([NotNull] ValidationMlParser.DimClauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.varRole"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarRole([NotNull] ValidationMlParser.VarRoleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.varRole"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarRole([NotNull] ValidationMlParser.VarRoleContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.bScalarExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBScalarExpr([NotNull] ValidationMlParser.BScalarExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.bScalarExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBScalarExpr([NotNull] ValidationMlParser.BScalarExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.sExprOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSExprOr([NotNull] ValidationMlParser.SExprOrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.sExprOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSExprOr([NotNull] ValidationMlParser.SExprOrContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.sExprAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSExprAnd([NotNull] ValidationMlParser.SExprAndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.sExprAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSExprAnd([NotNull] ValidationMlParser.SExprAndContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.sExprPredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSExprPredicate([NotNull] ValidationMlParser.SExprPredicateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.sExprPredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSExprPredicate([NotNull] ValidationMlParser.SExprPredicateContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.scalarExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScalarExpr([NotNull] ValidationMlParser.ScalarExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.scalarExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScalarExpr([NotNull] ValidationMlParser.ScalarExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.sExprAdd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSExprAdd([NotNull] ValidationMlParser.SExprAddContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.sExprAdd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSExprAdd([NotNull] ValidationMlParser.SExprAddContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.sExprFactor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSExprFactor([NotNull] ValidationMlParser.SExprFactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.sExprFactor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSExprFactor([NotNull] ValidationMlParser.SExprFactorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.sExprAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSExprAtom([NotNull] ValidationMlParser.SExprAtomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.sExprAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSExprAtom([NotNull] ValidationMlParser.SExprAtomContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.componentID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComponentID([NotNull] ValidationMlParser.ComponentIDContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.componentID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComponentID([NotNull] ValidationMlParser.ComponentIDContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.compOpScalarClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompOpScalarClause([NotNull] ValidationMlParser.CompOpScalarClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.compOpScalarClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompOpScalarClause([NotNull] ValidationMlParser.CompOpScalarClauseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.logBase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogBase([NotNull] ValidationMlParser.LogBaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.logBase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogBase([NotNull] ValidationMlParser.LogBaseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.powerExponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPowerExponent([NotNull] ValidationMlParser.PowerExponentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.powerExponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPowerExponent([NotNull] ValidationMlParser.PowerExponentContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.exponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExponent([NotNull] ValidationMlParser.ExponentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.exponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExponent([NotNull] ValidationMlParser.ExponentContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.setExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetExpr([NotNull] ValidationMlParser.SetExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.setExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetExpr([NotNull] ValidationMlParser.SetExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.varID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarID([NotNull] ValidationMlParser.VarIDContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.varID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarID([NotNull] ValidationMlParser.VarIDContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.compOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompOp([NotNull] ValidationMlParser.CompOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.compOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompOp([NotNull] ValidationMlParser.CompOpContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.compOpScalar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompOpScalar([NotNull] ValidationMlParser.CompOpScalarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.compOpScalar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompOpScalar([NotNull] ValidationMlParser.CompOpScalarContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] ValidationMlParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] ValidationMlParser.ConstantContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.isCompl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIsCompl([NotNull] ValidationMlParser.IsComplContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.isCompl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIsCompl([NotNull] ValidationMlParser.IsComplContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.lhperc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLhperc([NotNull] ValidationMlParser.LhpercContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.lhperc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLhperc([NotNull] ValidationMlParser.LhpercContext context);
}
} // namespace VTL_Editor_PL
