//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from G:\SOFTWARE\SW INTERNO\ParserVTL\VTL_Editor_PL\VTL_Editor_PL\ValidationMl.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace VTLlib {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
    using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IValidationMlListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public partial class ValidationMlBaseListener : IValidationMlListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] ValidationMlParser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] ValidationMlParser.StartContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] ValidationMlParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] ValidationMlParser.StatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] ValidationMlParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] ValidationMlParser.ExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.exprOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprOr([NotNull] ValidationMlParser.ExprOrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.exprOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprOr([NotNull] ValidationMlParser.ExprOrContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.exprAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprAnd([NotNull] ValidationMlParser.ExprAndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.exprAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprAnd([NotNull] ValidationMlParser.ExprAndContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.exprEq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprEq([NotNull] ValidationMlParser.ExprEqContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.exprEq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprEq([NotNull] ValidationMlParser.ExprEqContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.exprExists"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprExists([NotNull] ValidationMlParser.ExprExistsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.exprExists"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprExists([NotNull] ValidationMlParser.ExprExistsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.exprComp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprComp([NotNull] ValidationMlParser.ExprCompContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.exprComp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprComp([NotNull] ValidationMlParser.ExprCompContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.exprAdd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprAdd([NotNull] ValidationMlParser.ExprAddContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.exprAdd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprAdd([NotNull] ValidationMlParser.ExprAddContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.exprMultiply"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprMultiply([NotNull] ValidationMlParser.ExprMultiplyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.exprMultiply"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprMultiply([NotNull] ValidationMlParser.ExprMultiplyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.exprFactor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprFactor([NotNull] ValidationMlParser.ExprFactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.exprFactor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprFactor([NotNull] ValidationMlParser.ExprFactorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.exprMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprMember([NotNull] ValidationMlParser.ExprMemberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.exprMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprMember([NotNull] ValidationMlParser.ExprMemberContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.exprAtom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprAtom([NotNull] ValidationMlParser.ExprAtomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.exprAtom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprAtom([NotNull] ValidationMlParser.ExprAtomContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.variableRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableRef([NotNull] ValidationMlParser.VariableRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.variableRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableRef([NotNull] ValidationMlParser.VariableRefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.getExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGetExpr([NotNull] ValidationMlParser.GetExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.getExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGetExpr([NotNull] ValidationMlParser.GetExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.persistentDatasetID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPersistentDatasetID([NotNull] ValidationMlParser.PersistentDatasetIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.persistentDatasetID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPersistentDatasetID([NotNull] ValidationMlParser.PersistentDatasetIDContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.putExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPutExpr([NotNull] ValidationMlParser.PutExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.putExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPutExpr([NotNull] ValidationMlParser.PutExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.evalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEvalExpr([NotNull] ValidationMlParser.EvalExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.evalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEvalExpr([NotNull] ValidationMlParser.EvalExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.validationExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValidationExpr([NotNull] ValidationMlParser.ValidationExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.validationExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValidationExpr([NotNull] ValidationMlParser.ValidationExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.mergeExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMergeExpr([NotNull] ValidationMlParser.MergeExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.mergeExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMergeExpr([NotNull] ValidationMlParser.MergeExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.hierarchyExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHierarchyExpr([NotNull] ValidationMlParser.HierarchyExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.hierarchyExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHierarchyExpr([NotNull] ValidationMlParser.HierarchyExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.mappingExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMappingExpr([NotNull] ValidationMlParser.MappingExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.mappingExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMappingExpr([NotNull] ValidationMlParser.MappingExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.aggrParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAggrParam([NotNull] ValidationMlParser.AggrParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.aggrParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAggrParam([NotNull] ValidationMlParser.AggrParamContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.aggregategetClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAggregategetClause([NotNull] ValidationMlParser.AggregategetClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.aggregategetClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAggregategetClause([NotNull] ValidationMlParser.AggregategetClauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.aggregateClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAggregateClause([NotNull] ValidationMlParser.AggregateClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.aggregateClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAggregateClause([NotNull] ValidationMlParser.AggregateClauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.aggrFunctionClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAggrFunctionClause([NotNull] ValidationMlParser.AggrFunctionClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.aggrFunctionClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAggrFunctionClause([NotNull] ValidationMlParser.AggrFunctionClauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.datasetIDGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDatasetIDGroup([NotNull] ValidationMlParser.DatasetIDGroupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.datasetIDGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDatasetIDGroup([NotNull] ValidationMlParser.DatasetIDGroupContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.caseElseClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaseElseClause([NotNull] ValidationMlParser.CaseElseClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.caseElseClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaseElseClause([NotNull] ValidationMlParser.CaseElseClauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.caseCaseClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaseCaseClause([NotNull] ValidationMlParser.CaseCaseClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.caseCaseClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaseCaseClause([NotNull] ValidationMlParser.CaseCaseClauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.getFiltersClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGetFiltersClause([NotNull] ValidationMlParser.GetFiltersClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.getFiltersClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGetFiltersClause([NotNull] ValidationMlParser.GetFiltersClauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.getFilterClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGetFilterClause([NotNull] ValidationMlParser.GetFilterClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.getFilterClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGetFilterClause([NotNull] ValidationMlParser.GetFilterClauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.datasetClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDatasetClause([NotNull] ValidationMlParser.DatasetClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.datasetClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDatasetClause([NotNull] ValidationMlParser.DatasetClauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.aggrFilterClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAggrFilterClause([NotNull] ValidationMlParser.AggrFilterClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.aggrFilterClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAggrFilterClause([NotNull] ValidationMlParser.AggrFilterClauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.filterClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFilterClause([NotNull] ValidationMlParser.FilterClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.filterClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFilterClause([NotNull] ValidationMlParser.FilterClauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.ascdescClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAscdescClause([NotNull] ValidationMlParser.AscdescClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.ascdescClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAscdescClause([NotNull] ValidationMlParser.AscdescClauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.renameClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRenameClause([NotNull] ValidationMlParser.RenameClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.renameClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRenameClause([NotNull] ValidationMlParser.RenameClauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.aggrFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAggrFunction([NotNull] ValidationMlParser.AggrFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.aggrFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAggrFunction([NotNull] ValidationMlParser.AggrFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.percentileFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPercentileFunction([NotNull] ValidationMlParser.PercentileFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.percentileFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPercentileFunction([NotNull] ValidationMlParser.PercentileFunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.calcClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCalcClause([NotNull] ValidationMlParser.CalcClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.calcClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCalcClause([NotNull] ValidationMlParser.CalcClauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.attrCalcClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttrCalcClause([NotNull] ValidationMlParser.AttrCalcClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.attrCalcClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttrCalcClause([NotNull] ValidationMlParser.AttrCalcClauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.calcClauseItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCalcClauseItem([NotNull] ValidationMlParser.CalcClauseItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.calcClauseItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCalcClauseItem([NotNull] ValidationMlParser.CalcClauseItemContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.calcExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCalcExpr([NotNull] ValidationMlParser.CalcExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.calcExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCalcExpr([NotNull] ValidationMlParser.CalcExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.dropClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDropClause([NotNull] ValidationMlParser.DropClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.dropClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDropClause([NotNull] ValidationMlParser.DropClauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.dropClauseItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDropClauseItem([NotNull] ValidationMlParser.DropClauseItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.dropClauseItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDropClauseItem([NotNull] ValidationMlParser.DropClauseItemContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.keepClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeepClause([NotNull] ValidationMlParser.KeepClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.keepClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeepClause([NotNull] ValidationMlParser.KeepClauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.keepClauseItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeepClauseItem([NotNull] ValidationMlParser.KeepClauseItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.keepClauseItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeepClauseItem([NotNull] ValidationMlParser.KeepClauseItemContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.compareClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompareClause([NotNull] ValidationMlParser.CompareClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.compareClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompareClause([NotNull] ValidationMlParser.CompareClauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.inBetweenClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInBetweenClause([NotNull] ValidationMlParser.InBetweenClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.inBetweenClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInBetweenClause([NotNull] ValidationMlParser.InBetweenClauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.dimClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDimClause([NotNull] ValidationMlParser.DimClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.dimClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDimClause([NotNull] ValidationMlParser.DimClauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.varRole"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarRole([NotNull] ValidationMlParser.VarRoleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.varRole"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarRole([NotNull] ValidationMlParser.VarRoleContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.bScalarExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBScalarExpr([NotNull] ValidationMlParser.BScalarExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.bScalarExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBScalarExpr([NotNull] ValidationMlParser.BScalarExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.sExprOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSExprOr([NotNull] ValidationMlParser.SExprOrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.sExprOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSExprOr([NotNull] ValidationMlParser.SExprOrContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.sExprAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSExprAnd([NotNull] ValidationMlParser.SExprAndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.sExprAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSExprAnd([NotNull] ValidationMlParser.SExprAndContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.sExprPredicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSExprPredicate([NotNull] ValidationMlParser.SExprPredicateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.sExprPredicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSExprPredicate([NotNull] ValidationMlParser.SExprPredicateContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.scalarExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScalarExpr([NotNull] ValidationMlParser.ScalarExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.scalarExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScalarExpr([NotNull] ValidationMlParser.ScalarExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.sExprAdd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSExprAdd([NotNull] ValidationMlParser.SExprAddContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.sExprAdd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSExprAdd([NotNull] ValidationMlParser.SExprAddContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.sExprFactor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSExprFactor([NotNull] ValidationMlParser.SExprFactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.sExprFactor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSExprFactor([NotNull] ValidationMlParser.SExprFactorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.sExprAtom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSExprAtom([NotNull] ValidationMlParser.SExprAtomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.sExprAtom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSExprAtom([NotNull] ValidationMlParser.SExprAtomContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.componentID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComponentID([NotNull] ValidationMlParser.ComponentIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.componentID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComponentID([NotNull] ValidationMlParser.ComponentIDContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.compOpScalarClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompOpScalarClause([NotNull] ValidationMlParser.CompOpScalarClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.compOpScalarClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompOpScalarClause([NotNull] ValidationMlParser.CompOpScalarClauseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.logBase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogBase([NotNull] ValidationMlParser.LogBaseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.logBase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogBase([NotNull] ValidationMlParser.LogBaseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.powerExponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPowerExponent([NotNull] ValidationMlParser.PowerExponentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.powerExponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPowerExponent([NotNull] ValidationMlParser.PowerExponentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.exponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExponent([NotNull] ValidationMlParser.ExponentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.exponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExponent([NotNull] ValidationMlParser.ExponentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.setExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetExpr([NotNull] ValidationMlParser.SetExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.setExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetExpr([NotNull] ValidationMlParser.SetExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.varID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarID([NotNull] ValidationMlParser.VarIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.varID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarID([NotNull] ValidationMlParser.VarIDContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.compOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompOp([NotNull] ValidationMlParser.CompOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.compOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompOp([NotNull] ValidationMlParser.CompOpContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.compOpScalar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompOpScalar([NotNull] ValidationMlParser.CompOpScalarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.compOpScalar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompOpScalar([NotNull] ValidationMlParser.CompOpScalarContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant([NotNull] ValidationMlParser.ConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant([NotNull] ValidationMlParser.ConstantContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.isCompl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIsCompl([NotNull] ValidationMlParser.IsComplContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.isCompl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIsCompl([NotNull] ValidationMlParser.IsComplContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="ValidationMlParser.lhperc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLhperc([NotNull] ValidationMlParser.LhpercContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ValidationMlParser.lhperc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLhperc([NotNull] ValidationMlParser.LhpercContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace VTL_Editor_PL
