//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceConnector.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebServiceConnector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [All Constrains].
        /// </summary>
        internal static string AllConstrains
        {
            get
            {
                return ResourceManager.GetString("AllConstrains", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>

        //internal static System.Drawing.Bitmap dbsettings
        //{
        //    get
        //    {
        //        object obj = ResourceManager.GetObject("dbsettings", resourceCulture);
        //        return ((System.Drawing.Bitmap)(obj));
        //    }
        //}

        /// <summary>
        ///   Looks up a localized string similar to Peak Working set: {0} MB.
        /// </summary>
        internal static string DebugPeakWorkingSetFormat1
        {
            get
            {
                return ResourceManager.GetString("DebugPeakWorkingSetFormat1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Private memory size: {0} MB.
        /// </summary>
        internal static string DebugPrivateMemorySizeFormat1
        {
            get
            {
                return ResourceManager.GetString("DebugPrivateMemorySizeFormat1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HTTP protocol error code 401 -The web service requires authentication but authentication is disabled at Test Client.  Please enable HTTP Authentication and supply the credentials (user name and password) at the Settings tab,at Web Service Test..
        /// </summary>
        internal static string error_401_enableAuthentication
        {
            get
            {
                return ResourceManager.GetString("error_401_enableAuthentication", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HTTP protocol error code 401 - Authentication failed due to invalid credentials (user name and/or password)..
        /// </summary>
        internal static string error_401_invalid_cred
        {
            get
            {
                return ResourceManager.GetString("error_401_invalid_cred", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You need to provide the &quot;Dimension at Observation&quot; value!.
        /// </summary>
        internal static string Error_Dimension_at_Observation
        {
            get
            {
                return ResourceManager.GetString("Error_Dimension_at_Observation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HTTP protocol error code {0} - {1}.  {2}.
        /// </summary>
        internal static string error_http
        {
            get
            {
                return ResourceManager.GetString("error_http", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid SDMX Period. Valid formats are :
        ///&lt;4 digit year&gt;-&lt;period&gt;.
        ///E.g. 2003-02 (Monthly), 2001-Q4 (Quarterly), 1993 (Annual).
        ///Please refer to SDMX-ML Standard for more details..
        /// </summary>
        internal static string error_invalid_timeperiod
        {
            get
            {
                return ResourceManager.GetString("error_invalid_timeperiod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This dataflow doesn&apos;t appear to have a KeyFamilyRef.
        /// </summary>
        internal static string error_no_dsd
        {
            get
            {
                return ResourceManager.GetString("error_no_dsd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To start the test you need to provide a valid xml query. 
        ///The given SDMX Query is invalid..
        /// </summary>
        internal static string error_no_query_or_invalid
        {
            get
            {
                return ResourceManager.GetString("error_no_query_or_invalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selected file is invalid.
        /// </summary>
        internal static string error_Selected_file_is_invalid
        {
            get
            {
                return ResourceManager.GetString("error_Selected_file_is_invalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The given SDMX Query is invalid..
        /// </summary>
        internal static string error_the_given_SDMX_Query_is_invalid
        {
            get
            {
                return ResourceManager.GetString("error_the_given_SDMX_Query_is_invalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error_title
        {
            get
            {
                return ResourceManager.GetString("error_title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot find a connection string {0} in {1}.config.
        /// </summary>
        internal static string errorCannotFindConnectionStringFormat2
        {
            get
            {
                return ResourceManager.GetString("errorCannotFindConnectionStringFormat2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to While retrieving Category Scheme and Dataflows from Mapping Store..
        /// </summary>
        internal static string ErrorCategoryDataflowRetrieval
        {
            get
            {
                return ResourceManager.GetString("ErrorCategoryDataflowRetrieval", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not find KeyFamily.
        /// </summary>
        internal static string ErrorCouldNotFindKeyFamily
        {
            get
            {
                return ResourceManager.GetString("ErrorCouldNotFindKeyFamily", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DataGenerator encountered the following issue..
        /// </summary>
        internal static string errorDataGenerator
        {
            get
            {
                return ResourceManager.GetString("errorDataGenerator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DataRetriever encountered the following issue..
        /// </summary>
        internal static string errorDataRetriever
        {
            get
            {
                return ResourceManager.GetString("errorDataRetriever", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DSD {0} does not support cross-sectional datasets..
        /// </summary>
        internal static string ErrorDSDNotSupportCrossSectionalDatasets
        {
            get
            {
                return ResourceManager.GetString("ErrorDSDNotSupportCrossSectionalDatasets", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to While executing sql query.
        /// </summary>
        internal static string ErrorExecutingSqlQuery
        {
            get
            {
                return ResourceManager.GetString("ErrorExecutingSqlQuery", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to While Generating Data..
        /// </summary>
        internal static string ErrorGeneratingData
        {
            get
            {
                return ResourceManager.GetString("ErrorGeneratingData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The selected dataflow has incomplete mappings..
        /// </summary>
        internal static string ErrorIncompleMappingSet
        {
            get
            {
                return ResourceManager.GetString("ErrorIncompleMappingSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration. Please check and correct the following configuration file.
        /// </summary>
        internal static string errorInvalidConfiguration
        {
            get
            {
                return ResourceManager.GetString("errorInvalidConfiguration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error Invalid SDMX Period.
        /// </summary>
        internal static string ErrorInvalidSDMXPeriodTitle
        {
            get
            {
                return ResourceManager.GetString("ErrorInvalidSDMXPeriodTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The given XML text is invalid..
        /// </summary>
        internal static string errorInvalidXmlText
        {
            get
            {
                return ResourceManager.GetString("errorInvalidXmlText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To start the test you need to provide a valid xml query..
        /// </summary>
        internal static string ErrorNeedValidQuery
        {
            get
            {
                return ResourceManager.GetString("ErrorNeedValidQuery", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not find any Categorisations.
        /// </summary>
        internal static string errorNoCategorisations
        {
            get
            {
                return ResourceManager.GetString("errorNoCategorisations", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not find any Dataflows.
        /// </summary>
        internal static string errorNoDataflows
        {
            get
            {
                return ResourceManager.GetString("errorNoDataflows", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DSD {0} {1} does not have a Time Dimension. Only Cross-Sectional data may be requested..
        /// </summary>
        internal static string ErrorNoTimeDimensionFormat2
        {
            get
            {
                return ResourceManager.GetString("ErrorNoTimeDimensionFormat2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to While parsing SDMX XSD files.
        /// </summary>
        internal static string ErrorParsingSchemaFiles
        {
            get
            {
                return ResourceManager.GetString("ErrorParsingSchemaFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to While parsing SDMX Query.
        /// </summary>
        internal static string ErrorParsingSDMXQuery
        {
            get
            {
                return ResourceManager.GetString("ErrorParsingSDMXQuery", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error retrieving WSDL. {0}.
        /// </summary>
        internal static string ErrorParsingWsdlFormat1
        {
            get
            {
                return ResourceManager.GetString("ErrorParsingWsdlFormat1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to While retrieving data.
        /// </summary>
        internal static string ErrorRetrieveData
        {
            get
            {
                return ResourceManager.GetString("ErrorRetrieveData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to While retrieving Codelists from Mapping Store.
        /// </summary>
        internal static string ErrorRetrievingCodelists
        {
            get
            {
                return ResourceManager.GetString("ErrorRetrievingCodelists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error. Could not save configuration.Possible reasons are:
        ///- Old configuration files (see Installation guide/Uninstall section.)
        ///- You might not have permission to write to the configuration file. Changing destination folder might help.
        ///The error was: {0}.
        /// </summary>
        internal static string ErrorSavingConfigurationFormat1
        {
            get
            {
                return ResourceManager.GetString("ErrorSavingConfigurationFormat1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to StructureRetriever encountered the following issue..
        /// </summary>
        internal static string errorStructureRetriever
        {
            get
            {
                return ResourceManager.GetString("errorStructureRetriever", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error type:.
        /// </summary>
        internal static string ErrorType
        {
            get
            {
                return ResourceManager.GetString("ErrorType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to While Generating SQL..
        /// </summary>
        internal static string ErrorWhileGeneratingSql
        {
            get
            {
                return ResourceManager.GetString("ErrorWhileGeneratingSql", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HTTP Settings.
        /// </summary>
        internal static string HTTPSettings
        {
            get
            {
                return ResourceManager.GetString("HTTPSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The operation was successfully completed..
        /// </summary>
        internal static string InfoCompleted
        {
            get
            {
                return ResourceManager.GetString("InfoCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The SDMX Query or SOAP message is not valid.{0}.
        /// </summary>
        internal static string InvalidDataRequestMessageFormat1
        {
            get
            {
                return ResourceManager.GetString("InvalidDataRequestMessageFormat1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}+{1}+{2}.
        /// </summary>
        internal static string KeyFormat3
        {
            get
            {
                return ResourceManager.GetString("KeyFormat3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Load Sdmx query from file....
        /// </summary>
        internal static string LoadSdmxQueryFromFile
        {
            get
            {
                return ResourceManager.GetString("LoadSdmxQueryFromFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Load an SDMX-ML Query from a file..
        /// </summary>
        internal static string LoadSDMXQueryFromFileTooltip
        {
            get
            {
                return ResourceManager.GetString("LoadSDMXQueryFromFileTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The category {0} has validation errors.
        /// </summary>
        internal static string LogCategoryValidationErrors
        {
            get
            {
                return ResourceManager.GetString("LogCategoryValidationErrors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The dataflow {0} has validation errors.
        /// </summary>
        internal static string LogDataflowValidationErrors
        {
            get
            {
                return ResourceManager.GetString("LogDataflowValidationErrors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There isn&apos;t enough memory to display this DataSet.
        /// </summary>
        internal static string outofmemory_error
        {
            get
            {
                return ResourceManager.GetString("outofmemory_error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to REST Service Test Form - Please wait.
        /// </summary>
        internal static string RestServiceTestPleaseWait
        {
            get
            {
                return ResourceManager.GetString("RestServiceTestPleaseWait", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to REST Service Test Form.
        /// </summary>
        internal static string RestServiceTestTitle
        {
            get
            {
                return ResourceManager.GetString("RestServiceTestTitle", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        //internal static System.Drawing.Bitmap shutdown
        //{
        //    get
        //    {
        //        object obj = ResourceManager.GetObject("shutdown", resourceCulture);
        //        return ((System.Drawing.Bitmap)(obj));
        //    }
        //}

        /// <summary>
        ///   Looks up a localized string similar to Test Client.
        /// </summary>
        internal static string title
        {
            get
            {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Test Client- Please wait.
        /// </summary>
        internal static string title_please_wait
        {
            get
            {
                return ResourceManager.GetString("title_please_wait", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to open the File {0}. Error was:.
        /// </summary>
        internal static string UnableToOpenFileFormat1
        {
            get
            {
                return ResourceManager.GetString("UnableToOpenFileFormat1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To start the test you need to provide a valid xml query. 
        ///Select a file using the Browse button or 
        ///manually write it in the Process SDMX Query Box.
        /// </summary>
        internal static string warning_invalid_xml_query
        {
            get
            {
                return ResourceManager.GetString("warning_invalid_xml_query", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Before executing it you need to have the SQL Generated. 
        ///Use the Generate SQL button.
        /// </summary>
        internal static string warning_nosqlgenerated
        {
            get
            {
                return ResourceManager.GetString("warning_nosqlgenerated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Some categories have validation errors:.
        /// </summary>
        internal static string WarningCategoriesValidationErrors
        {
            get
            {
                return ResourceManager.GetString("WarningCategoriesValidationErrors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Some dataflows have validation errors: {0}. Also some categories have validation errors: {1}..
        /// </summary>
        internal static string WarningDataflowsCategoriesValidationErrors
        {
            get
            {
                return ResourceManager.GetString("WarningDataflowsCategoriesValidationErrors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Some dataflows have validation errors:.
        /// </summary>
        internal static string WarningDataflowValidationErrors
        {
            get
            {
                return ResourceManager.GetString("WarningDataflowValidationErrors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Warning, found {0} Keyfamilies, expected 1.
        /// </summary>
        internal static string WarningFoundXDSDFormat1
        {
            get
            {
                return ResourceManager.GetString("WarningFoundXDSDFormat1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Warning! The output text is truncated because the result is too big. To increase the truncation limit please contact the System Administrator..
        /// </summary>
        internal static string WarningTruncatedResult
        {
            get
            {
                return ResourceManager.GetString("WarningTruncatedResult", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Web Service Testing error.
        /// </summary>
        internal static string WebServiceTestingErrorTitle
        {
            get
            {
                return ResourceManager.GetString("WebServiceTestingErrorTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Web Service Test form - Please wait.
        /// </summary>
        internal static string WebServiceTestPleaseWait
        {
            get
            {
                return ResourceManager.GetString("WebServiceTestPleaseWait", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Web Service Test form.
        /// </summary>
        internal static string WebServiceTestTitle
        {
            get
            {
                return ResourceManager.GetString("WebServiceTestTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to open the Open File Dialog. Error was:.
        /// </summary>
        internal static string WindowsApplication_BtnBrowseClick_Unable_to_open_the_Open_File_Dialog__Error_was
        {
            get
            {
                return ResourceManager.GetString("WindowsApplication_BtnBrowseClick_Unable_to_open_the_Open_File_Dialog__Error_was", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to While loading mapping store configuration..
        /// </summary>
        internal static string WindowsApplication_InitializeConnectionString_While_loading_mapping_store_configuration_
        {
            get
            {
                return ResourceManager.GetString("WindowsApplication_InitializeConnectionString_While_loading_mapping_store_configu" +
                        "ration_", resourceCulture);
            }
        }
    }
}
